# name: Build
# on: [push, pull_request]

# permissions:
#   contents: read

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v5
#       - name: Set up JDK
#         uses: actions/setup-java@v4
#         with:
#           java-version: 21
#           distribution: 'temurin'
#       - name: Build with Maven
#         run: mvn --batch-mode --update-snapshots verify
#       - name: Upload coverage to codecov (tokenless)
#         if: >-
#           github.event_name == 'pull_request' &&
#           github.event.pull_request.head.repo.full_name != github.repository
#         uses: codecov/codecov-action@v5
#         with:
#           fail_ci_if_error: true
#       - name: Upload coverage to codecov (with token)
#         if: >
#           github.repository == 'TheAlgorithms/Java' &&
#           (github.event_name != 'pull_request' ||
#           github.event.pull_request.head.repo.full_name == github.repository)
#         uses: codecov/codecov-action@v5
#         with:
#           token: ${{ secrets.CODECOV_TOKEN }}
#           fail_ci_if_error: true
#       - name: Checkstyle
#         run: mvn checkstyle:check
#       - name: SpotBugs
#         run: mvn spotbugs:check
#       - name: PMD
#         run: mvn pmd:check
name: Java CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Compile Java files
      - name: Compile Java
        run: javac -d out $(find . -name "*.java")

      # (Optional) Run Java program if you have a Main class
      - name: Run tests (if any)
        run: |
          if [ -f out/Main.class ]; then
            java -cp out Main
          else
            echo "No Main class found, skipping run."
          fi
